/**
 * Integration tests for MCP tools against CLI-initialized projects
 *
 * Tests the RaftersToolHandler against projects initialized via `rafters init`.
 * This validates the full pipeline: CLI creates tokens -> MCP reads and serves them.
 */

import { afterEach, describe, expect, it } from 'vitest';
import { cleanupFixture } from '../fixtures/projects.js';
import { RaftersToolHandler } from '../../src/mcp/tools.js';
import { createInitializedFixture, execCli } from './helpers.js';

let fixturePath = '';

afterEach(async () => {
  if (fixturePath) {
    await cleanupFixture(fixturePath);
    fixturePath = '';
  }
});

describe('MCP tools against initialized project', () => {
  it('rafters_vocabulary returns tokens generated by init', async () => {
    fixturePath = await createInitializedFixture('nextjs-shadcn-v4');
    const handler = new RaftersToolHandler(fixturePath);

    const result = await handler.handleToolCall('rafters_vocabulary', {});

    expect(result.isError).toBeFalsy();
    const data = JSON.parse(result.content[0].text as string);

    // System preamble always present
    expect(data.system).toContain('RAFTERS IS NOT SHADCN');

    // Color tokens from CLI init should be present
    expect(data.colors.semantic).toContain('primary');
    expect(data.colors.semantic).toContain('destructive');
    expect(data.colors.semantic).toContain('success');
    expect(data.colors.semantic).toContain('warning');

    // Spacing from CLI-generated tokens
    expect(Object.keys(data.spacing.scale).length).toBeGreaterThan(0);

    // Typography
    expect(Object.keys(data.typography.sizes).length).toBeGreaterThan(0);

    // Patterns
    expect(data.patterns).toContain('destructive-action');
    expect(data.patterns).toContain('form-validation');

    // Components
    expect(data.components.installed).toEqual([]);
    expect(data.components.available.length).toBeGreaterThan(0);
  }, 30000);

  it('rafters_token returns spacing token details from CLI-initialized project', async () => {
    fixturePath = await createInitializedFixture('vite-no-shadcn');
    const handler = new RaftersToolHandler(fixturePath);

    const result = await handler.handleToolCall('rafters_token', {
      name: 'spacing-1',
    });

    expect(result.isError).toBeFalsy();
    const data = JSON.parse(result.content[0].text as string);

    expect(data.name).toBe('spacing-1');
    expect(data.namespace).toBe('spacing');
    expect(data.value).toBe('0.25rem');
  }, 30000);

  it('rafters_pattern works without project-specific tokens', async () => {
    fixturePath = await createInitializedFixture('vite-no-shadcn');
    const handler = new RaftersToolHandler(fixturePath);

    const result = await handler.handleToolCall('rafters_pattern', {
      pattern: 'form-validation',
    });

    expect(result.isError).toBeFalsy();
    const data = JSON.parse(result.content[0].text as string);

    expect(data.name).toBe('Form Validation');
    expect(data.components).toContain('field');
    expect(data.components).toContain('input');
    expect(data.accessibility).toBeDefined();
  }, 30000);

  it('rafters_cognitive_budget evaluates against initialized project', async () => {
    fixturePath = await createInitializedFixture('nextjs-shadcn-v4');
    const handler = new RaftersToolHandler(fixturePath);

    const result = await handler.handleToolCall('rafters_cognitive_budget', {
      components: ['button', 'card', 'dialog'],
      tier: 'page',
    });

    expect(result.isError).toBeFalsy();
    const data = JSON.parse(result.content[0].text as string);

    expect(data.budget.tier).toBe('page');
    expect(data.budget.budget).toBe(30);
    expect(data.budget.total).toBeGreaterThan(0);
    expect(data.components.length).toBeGreaterThan(0);
  }, 30000);

  it('vocabulary reflects installed components from config', async () => {
    fixturePath = await createInitializedFixture('nextjs-shadcn-v4');

    // Modify config to include installed components
    const { writeFile, readFile } = await import('node:fs/promises');
    const { join } = await import('node:path');
    const configPath = join(fixturePath, '.rafters', 'config.rafters.json');
    const config = JSON.parse(await readFile(configPath, 'utf-8'));
    config.installed = {
      components: ['button', 'card'],
      primitives: ['classy'],
      composites: [],
    };
    await writeFile(configPath, JSON.stringify(config, null, 2));

    const handler = new RaftersToolHandler(fixturePath);
    const result = await handler.handleToolCall('rafters_vocabulary', {});
    const data = JSON.parse(result.content[0].text as string);

    expect(data.components.installed).toEqual(['button', 'card']);
    expect(data.components.available).not.toContain('button');
    expect(data.components.available).not.toContain('card');
  }, 30000);
});

describe('MCP tools with null project root', () => {
  it('returns error for tools that require a project', async () => {
    const handler = new RaftersToolHandler(null);

    const vocabResult = await handler.handleToolCall('rafters_vocabulary', {});
    expect(vocabResult.isError).toBe(true);
    expect(vocabResult.content[0].text).toContain('pnpm dlx rafters init');

    const tokenResult = await handler.handleToolCall('rafters_token', { name: 'primary' });
    expect(tokenResult.isError).toBe(true);

    const budgetResult = await handler.handleToolCall('rafters_cognitive_budget', {
      components: ['button'],
    });
    expect(budgetResult.isError).toBe(true);
  });

  it('rafters_pattern works without a project root', async () => {
    const handler = new RaftersToolHandler(null);

    const result = await handler.handleToolCall('rafters_pattern', {
      pattern: 'destructive-action',
    });

    expect(result.isError).toBeFalsy();
    const data = JSON.parse(result.content[0].text as string);
    expect(data.name).toBe('Destructive Action');
  });
});

describe('MCP tools after rebuild', () => {
  it('tools return consistent data after init --rebuild', async () => {
    fixturePath = await createInitializedFixture('nextjs-shadcn-v4');

    // Get vocabulary before rebuild
    const handler1 = new RaftersToolHandler(fixturePath);
    const result1 = await handler1.handleToolCall('rafters_vocabulary', {});
    const data1 = JSON.parse(result1.content[0].text as string);

    // Rebuild
    await execCli(fixturePath, ['init', '--rebuild']);

    // Get vocabulary after rebuild
    const handler2 = new RaftersToolHandler(fixturePath);
    const result2 = await handler2.handleToolCall('rafters_vocabulary', {});
    const data2 = JSON.parse(result2.content[0].text as string);

    // Token counts should match
    expect(data2.colors.semantic.length).toBe(data1.colors.semantic.length);
    expect(Object.keys(data2.spacing.scale).length).toBe(
      Object.keys(data1.spacing.scale).length,
    );
  }, 30000);
});
