/**
 * Hub/Spoke Color Name Data Structure
 *
 * Each hue hub contains semantically-appropriate color names organized by
 * lightness and chroma bands. The hub (hue) is the semantic anchor - it
 * determines what kind of color this is. The spokes (L×C matrix) contain
 * words that are semantically compatible with both the hue AND the L/C values.
 *
 * Structure:
 * - 18 hue hubs (20° each)
 * - Each hub has a 5×4 matrix (L bands × C bands)
 * - Each cell contains 10+ semantically-appropriate words
 * - Temperature selects which hub variant to use
 * - Fractional L/C values sub-select within the word list
 *
 * RESERVED SEGMENTS (#1637): no entry may be 'to', 'via', or 'from', nor
 * contain one as a hyphen segment (e.g. 'door-to-door' is forbidden;
 * 'tomato' and 'torch' are fine). The fill signature parser splits names
 * on '-to-'. Enforced by the reservation test in test/naming.test.ts.
 */

/**
 * Lightness bands (5 levels)
 * Maps to L bucket ranges for semantic compatibility
 */
export type LightnessBand = 'veryDark' | 'dark' | 'mid' | 'light' | 'veryLight';

/**
 * Chroma bands (4 levels)
 * Maps to C bucket ranges for semantic compatibility
 */
export type ChromaBand = 'muted' | 'moderate' | 'saturated' | 'vivid';

/**
 * A cell in the L×C matrix containing semantically-appropriate words
 */
export type HueCell = readonly string[];

/**
 * The L×C matrix for a single hue hub
 * Organized as [LightnessBand][ChromaBand] → words[]
 */
export type HueMatrix = {
  readonly [L in LightnessBand]: {
    readonly [C in ChromaBand]: HueCell;
  };
};

/**
 * A complete hue hub with temperature variants
 */
export type HueHub = {
  readonly warm: HueMatrix;
  readonly cool: HueMatrix;
  readonly neutral: HueMatrix;
};

/**
 * Map L bucket (0-9) to lightness band
 */
export function getLightnessBand(lBucket: number): LightnessBand {
  if (lBucket <= 1) return 'veryDark'; // 0.0-0.2
  if (lBucket <= 3) return 'dark'; // 0.2-0.4
  if (lBucket <= 5) return 'mid'; // 0.4-0.6
  if (lBucket <= 7) return 'light'; // 0.6-0.8
  return 'veryLight'; // 0.8-1.0
}

/**
 * Map C bucket (0-7) to chroma band
 */
export function getChromaBand(cBucket: number): ChromaBand {
  if (cBucket <= 1) return 'muted'; // 0.00-0.06
  if (cBucket <= 3) return 'moderate'; // 0.06-0.15
  if (cBucket <= 5) return 'saturated'; // 0.15-0.25
  return 'vivid'; // 0.25+
}

/**
 * Calculate sub-index within a word list using fractional position
 * This uses the "leftover" precision after bucketing to deterministically
 * select which synonym to use.
 *
 * @param value - The original L, C, or H value
 * @param bucketSize - The size of each bucket
 * @param wordCount - Number of words available in the cell
 * @returns Index into the word array (0 to wordCount-1)
 */
export function getSubIndex(value: number, bucketSize: number, wordCount: number): number {
  if (wordCount <= 1) return 0;
  // Get position within bucket (0.0 to 1.0)
  const withinBucket = (value % bucketSize) / bucketSize;
  // Map to word index
  return Math.min(Math.floor(withinBucket * wordCount), wordCount - 1);
}

// ============================================================================
// HUE HUBS - Organized by hue angle
// ============================================================================

/**
 * Red Hub (0-20°)
 * Core semantic: fire, blood, passion, danger, warmth
 */
export const RED_HUB: HueHub = {
  warm: {
    veryDark: {
      muted: [
        'oxblood',
        'dried-blood',
        'old-brick',
        'dark-clay',
        'burnt-earth',
        'aged-wine',
        'dark-rust',
        'iron-oxide',
        'terra-preta',
        'dark-madder',
      ],
      moderate: [
        'mahogany',
        'maroon',
        'burgundy',
        'cordovan',
        'wine',
        'blood',
        'liver',
        'puce',
        'dark-cherry',
        'mulled-wine',
      ],
      saturated: [
        'crimson',
        'carmine',
        'garnet',
        'ruby-dark',
        'pomegranate',
        'cranberry',
        'dark-scarlet',
        'blood-red',
        'oxheart',
        'pigeon-blood',
      ],
      vivid: [
        'blood-orange',
        'vermillion-dark',
        'firebrick',
        'dark-flame',
        'ember-glow',
        'molten-core',
        'lava-dark',
        'hot-coal',
        'inferno-dark',
        'dragon-blood',
      ],
    },
    dark: {
      muted: [
        'brick',
        'terracotta-dark',
        'rust',
        'dried-rose',
        'faded-barn',
        'weathered-brick',
        'old-copper',
        'patina-red',
        'dusty-cedar',
        'clay-pot',
      ],
      moderate: [
        'auburn',
        'chestnut',
        'russet',
        'sienna-red',
        'cinnamon-bark',
        'redwood',
        'sequoia',
        'cedar',
        'cayenne',
        'paprika',
      ],
      saturated: [
        'ruby',
        'cardinal',
        'cherry',
        'apple-red',
        'fire-engine',
        'candy-apple',
        'lipstick',
        'lacquer-red',
        'enamel-red',
        'geranium',
      ],
      vivid: [
        'scarlet',
        'vermillion',
        'flame',
        'blaze',
        'fire',
        'torch',
        'signal-red',
        'racing-red',
        'ferrari',
        'hot-rod',
      ],
    },
    mid: {
      muted: [
        'salmon-dark',
        'dusty-rose',
        'old-rose',
        'rosewood',
        'mauve-red',
        'antique-rose',
        'canyon-rose',
        'desert-rose',
        'adobe',
        'terra-rosa',
      ],
      moderate: [
        'coral-red',
        'poppy',
        'tomato',
        'pepper',
        'hibiscus',
        'carnation',
        'zinnia',
        'dahlia-red',
        'begonia',
        'impatiens',
      ],
      saturated: [
        'red',
        'true-red',
        'primary-red',
        'pure-red',
        'stop-sign',
        'fire-truck',
        'emergency',
        'alert-red',
        'danger',
        'warning-red',
      ],
      vivid: [
        'neon-red',
        'electric-red',
        'laser-red',
        'fluorescent-red',
        'hot-red',
        'vivid-red',
        'intense-red',
        'brilliant-red',
        'radiant-red',
        'blazing-red',
      ],
    },
    light: {
      muted: [
        'salmon',
        'rose-dust',
        'blush-pink',
        'dusty-pink',
        'muted-coral',
        'faded-rose',
        'vintage-rose',
        'tea-rose',
        'pressed-rose',
        'dried-petal',
      ],
      moderate: [
        'coral',
        'peach-red',
        'guava',
        'watermelon',
        'grapefruit',
        'papaya',
        'melon-red',
        'cantaloupe-blush',
        'apricot-red',
        'mango-red',
      ],
      saturated: [
        'light-red',
        'bright-coral',
        'strawberry',
        'raspberry-light',
        'cherry-blossom',
        'rose-red',
        'petal-red',
        'bloom-red',
        'spring-red',
        'fresh-red',
      ],
      vivid: [
        'hot-pink-red',
        'electric-coral',
        'neon-salmon',
        'vivid-coral',
        'bright-flame',
        'sunrise-red',
        'dawn-red',
        'morning-glory-red',
        'tropical-red',
        'paradise-red',
      ],
    },
    veryLight: {
      muted: [
        'blush',
        'rose-quartz',
        'powder-pink',
        'baby-pink',
        'shell-pink',
        'petal-pink',
        'whisper-pink',
        'ballet-pink',
        'tutu',
        'fairy-pink',
      ],
      moderate: [
        'light-coral',
        'peach-bloom',
        'rose-petal',
        'cherry-cream',
        'strawberry-cream',
        'rose-milk',
        'petal-soft',
        'blossom-pink',
        'spring-bloom',
        'garden-pink',
      ],
      saturated: [
        'bright-pink',
        'candy-pink',
        'bubblegum',
        'cotton-candy',
        'flamingo',
        'pink-lemonade',
        'raspberry-sorbet',
        'strawberry-ice',
        'rose-ice',
        'cherry-ice',
      ],
      vivid: [
        'hot-pink',
        'neon-pink',
        'electric-pink',
        'shocking-pink',
        'fuchsia-light',
        'magenta-light',
        'vivid-pink',
        'radiant-pink',
        'brilliant-pink',
        'laser-pink',
      ],
    },
  },
  cool: {
    veryDark: {
      muted: [
        'dried-blood',
        'old-wine',
        'aged-burgundy',
        'dark-plum-red',
        'bruised-cherry',
        'blackened-rose',
        'shadow-red',
        'eclipse-red',
        'midnight-red',
        'abyss-red',
      ],
      moderate: [
        'bordeaux',
        'merlot',
        'cabernet',
        'pinot-noir',
        'claret',
        'port',
        'sherry-dark',
        'sangria-dark',
        'mulberry-wine',
        'blackberry-wine',
      ],
      saturated: [
        'deep-crimson',
        'blood-ruby',
        'garnet-dark',
        'dark-cherry',
        'black-cherry',
        'morello',
        'bing-cherry',
        'oxheart-dark',
        'heart-blood',
        'arterial',
      ],
      vivid: [
        'dark-magenta-red',
        'deep-cerise',
        'dark-rose',
        'wine-red',
        'vampire-red',
        'gothic-red',
        'velvet-red',
        'theatre-red',
        'curtain-red',
        'drama-red',
      ],
    },
    dark: {
      muted: [
        'dusty-burgundy',
        'faded-wine',
        'aged-rose',
        'antique-red',
        'weathered-rose',
        'faded-crimson',
        'muted-cherry',
        'soft-maroon',
        'gentle-burgundy',
        'quiet-red',
      ],
      moderate: [
        'raspberry-dark',
        'boysenberry',
        'loganberry',
        'mulberry',
        'blackcurrant-red',
        'currant',
        'jam',
        'preserve-red',
        'compote',
        'reduction',
      ],
      saturated: [
        'cherry-wine',
        'berry-red',
        'cranberry-dark',
        'pomegranate-dark',
        'red-grape',
        'red-plum',
        'damson-red',
        'sloe-red',
        'bramble-red',
        'hedgerow-red',
      ],
      vivid: [
        'magenta-red',
        'cerise-dark',
        'rose-red-dark',
        'fuchsia-red',
        'amaranth-dark',
        'crimson-rose',
        'rose-crimson',
        'berry-vivid',
        'jewel-red',
        'gem-red',
      ],
    },
    mid: {
      muted: [
        'mauve-rose',
        'dusty-raspberry',
        'muted-berry',
        'soft-cherry',
        'quiet-rose',
        'gentle-red',
        'calm-rose',
        'serene-red',
        'peaceful-rose',
        'tender-red',
      ],
      moderate: [
        'raspberry',
        'red-violet',
        'rose-wine',
        'berry',
        'currant-red',
        'jam-red',
        'preserve',
        'fruit-red',
        'harvest-red',
        'orchard-red',
      ],
      saturated: [
        'amaranth',
        'cerise',
        'rose-red',
        'cherry-red',
        'berry-bright',
        'fruit-punch',
        'punch-red',
        'sangria',
        'mixed-berry',
        'summer-red',
      ],
      vivid: [
        'magenta',
        'fuchsia-red',
        'electric-rose',
        'neon-cerise',
        'hot-rose',
        'vivid-rose',
        'brilliant-rose',
        'radiant-rose',
        'laser-rose',
        'plasma-rose',
      ],
    },
    light: {
      muted: [
        'dusty-rose-light',
        'muted-pink',
        'soft-rose',
        'gentle-pink',
        'quiet-blush',
        'calm-rose',
        'serene-pink',
        'peaceful-blush',
        'tender-rose',
        'delicate-pink',
      ],
      moderate: [
        'rose',
        'pink-rose',
        'tea-rose-light',
        'garden-rose',
        'english-rose',
        'damask-rose',
        'cabbage-rose',
        'peony-pink',
        'carnation-pink',
        'sweet-william',
      ],
      saturated: [
        'bright-rose',
        'vivid-pink',
        'rose-bright',
        'cherry-pink',
        'berry-pink',
        'raspberry-pink',
        'strawberry-pink',
        'fruit-pink',
        'candy-rose',
        'sweet-rose',
      ],
      vivid: [
        'hot-rose',
        'electric-rose-light',
        'neon-rose',
        'fluorescent-rose',
        'laser-rose-light',
        'plasma-pink',
        'vivid-rose-light',
        'brilliant-rose-light',
        'radiant-rose-light',
        'glowing-rose',
      ],
    },
    veryLight: {
      muted: [
        'pale-rose',
        'whisper-rose',
        'ghost-pink',
        'phantom-rose',
        'mist-pink',
        'fog-rose',
        'cloud-pink',
        'dream-rose',
        'ethereal-pink',
        'spirit-rose',
      ],
      moderate: [
        'light-rose',
        'rose-cream',
        'pink-cream',
        'rose-milk',
        'strawberry-milk',
        'cherry-cream',
        'berry-cream',
        'fruit-cream',
        'blossom-cream',
        'petal-cream',
      ],
      saturated: [
        'bright-rose-light',
        'vivid-rose-pale',
        'rose-ice',
        'pink-ice',
        'frozen-rose',
        'crystal-pink',
        'diamond-rose',
        'gem-pink',
        'jewel-rose',
        'precious-pink',
      ],
      vivid: [
        'neon-rose-light',
        'electric-pink-pale',
        'hot-pink-light',
        'shocking-pink-light',
        'vivid-pink-light',
        'brilliant-pink-light',
        'radiant-pink-light',
        'glowing-pink',
        'luminous-pink',
        'phosphor-pink',
      ],
    },
  },
  neutral: {
    veryDark: {
      muted: [
        'dark-taupe-red',
        'shadowed-clay',
        'deep-earth-red',
        'dark-adobe',
        'burnt-sienna-dark',
        'raw-umber-red',
        'dark-ochre-red',
        'iron-earth',
        'ferrous-clay',
        'mineral-red',
      ],
      moderate: [
        'indian-red-dark',
        'venetian-red-dark',
        'english-red-dark',
        'mars-red',
        'oxide-red',
        'iron-red',
        'hematite',
        'jasper-dark',
        'carnelian-dark',
        'sardonyx',
      ],
      saturated: [
        'cadmium-red-dark',
        'chinese-red-dark',
        'dragon-red',
        'lacquer-dark',
        'cinnabar-dark',
        'vermillion-dark-neutral',
        'mineral-vermillion',
        'natural-red',
        'earth-crimson',
        'clay-crimson',
      ],
      vivid: [
        'spectrum-red-dark',
        'true-red-dark',
        'primary-red-dark',
        'pure-red-dark',
        'essential-red-dark',
        'fundamental-red',
        'base-red-dark',
        'core-red',
        'central-red',
        'heart-red',
      ],
    },
    dark: {
      muted: [
        'indian-red',
        'venetian-red',
        'english-red',
        'persian-red',
        'turkish-red',
        'morocco-red',
        'arabian-red',
        'sahara-red',
        'desert-red',
        'canyon-red',
      ],
      moderate: [
        'brick-red',
        'tile-red',
        'roof-red',
        'pottery-red',
        'ceramic-red',
        'terracotta',
        'earthenware',
        'stoneware-red',
        'kiln-red',
        'fired-clay',
      ],
      saturated: [
        'cadmium-red',
        'chinese-red',
        'cinnabar',
        'vermillion-neutral',
        'lacquer',
        'enamel',
        'glaze-red',
        'porcelain-red',
        'china-red',
        'oriental-red',
      ],
      vivid: [
        'spectrum-red',
        'true-red-neutral',
        'primary',
        'pure',
        'essential-red',
        'fundamental',
        'base-red',
        'standard-red',
        'reference-red',
        'calibration-red',
      ],
    },
    mid: {
      muted: [
        'salmon-neutral',
        'terra-cotta-light',
        'adobe-light',
        'pueblo',
        'mesa',
        'butte',
        'sedona',
        'moab',
        'arches',
        'canyon-light',
      ],
      moderate: [
        'coral-neutral',
        'sunset',
        'sunrise',
        'dawn',
        'dusk',
        'twilight-red',
        'horizon',
        'skyline-red',
        'atmosphere',
        'ambient-red',
      ],
      saturated: [
        'red-neutral',
        'balanced-red',
        'centered-red',
        'median-red',
        'middle-red',
        'mean-red',
        'average-red',
        'typical-red',
        'common-red',
        'standard',
      ],
      vivid: [
        'vivid-red-neutral',
        'intense-neutral',
        'strong-red',
        'powerful-red',
        'forceful-red',
        'dynamic-red',
        'energetic-red',
        'active-red',
        'vital-red',
        'living-red',
      ],
    },
    light: {
      muted: [
        'peach',
        'apricot',
        'melon',
        'cantaloupe',
        'papaya-light',
        'mango-light',
        'guava-light',
        'passion-fruit',
        'tropical-peach',
        'island-coral',
      ],
      moderate: [
        'light-coral-neutral',
        'shell',
        'conch',
        'nautilus',
        'scallop',
        'oyster-pink',
        'pearl-pink',
        'mother-of-pearl-pink',
        'abalone-pink',
        'sea-shell',
      ],
      saturated: [
        'bright-coral-neutral',
        'reef',
        'lagoon-coral',
        'tropical-coral',
        'island-coral-bright',
        'pacific-coral',
        'caribbean-coral',
        'atlantic-coral',
        'mediterranean-coral',
        'aegean-coral',
      ],
      vivid: [
        'electric-coral',
        'neon-coral',
        'fluorescent-coral',
        'phosphor-coral',
        'luminous-coral',
        'glowing-coral',
        'radiant-coral',
        'brilliant-coral-neutral',
        'vivid-coral-neutral',
        'intense-coral',
      ],
    },
    veryLight: {
      muted: [
        'nude',
        'skin',
        'flesh',
        'complexion',
        'bisque',
        'porcelain-skin',
        'ivory-skin',
        'cream-skin',
        'milk-skin',
        'pearl-skin',
      ],
      moderate: [
        'peach-cream',
        'apricot-cream',
        'melon-cream',
        'fruit-cream-neutral',
        'blossom-white',
        'petal-white',
        'flower-white',
        'bloom-white',
        'spring-white',
        'garden-white',
      ],
      saturated: [
        'pink-white',
        'rose-white',
        'blush-white',
        'coral-white',
        'salmon-white',
        'peach-white',
        'apricot-white',
        'melon-white',
        'fruit-white',
        'tropical-white',
      ],
      vivid: [
        'bright-blush',
        'vivid-nude',
        'intense-peach',
        'strong-blush',
        'powerful-pink-white',
        'dynamic-blush',
        'energetic-nude',
        'active-peach',
        'vital-blush',
        'living-pink',
      ],
    },
  },
};

/**
 * Blue Hub (220-240°)
 * Core semantic: sky, ocean, trust, calm, depth
 */
export const BLUE_HUB: HueHub = {
  warm: {
    veryDark: {
      muted: [
        'dark-denim',
        'worn-navy',
        'faded-indigo',
        'old-blue',
        'aged-blue',
        'weathered-blue',
        'antique-blue',
        'vintage-navy',
        'heritage-blue',
        'classic-navy',
      ],
      moderate: [
        'navy',
        'midnight',
        'dark-navy',
        'deep-navy',
        'true-navy',
        'naval',
        'admiral',
        'commodore',
        'captain-blue',
        'officer-blue',
      ],
      saturated: [
        'prussian',
        'berlin-blue',
        'paris-blue',
        'french-navy',
        'royal-dark',
        'imperial-blue',
        'regal-blue',
        'noble-blue',
        'sovereign-blue',
        'crown-blue',
      ],
      vivid: [
        'electric-navy',
        'vivid-navy',
        'intense-navy',
        'deep-electric',
        'dark-laser',
        'night-electric',
        'midnight-vivid',
        'dark-neon',
        'deep-glow',
        'abyss-electric',
      ],
    },
    dark: {
      muted: [
        'slate-blue',
        'blue-gray',
        'steel-blue-dark',
        'iron-blue',
        'gunmetal-blue',
        'battleship-blue',
        'charcoal-blue',
        'ash-blue',
        'smoke-blue',
        'fog-blue-dark',
      ],
      moderate: [
        'denim',
        'jean-blue',
        'work-blue',
        'uniform-blue',
        'service-blue',
        'utility-blue',
        'industrial-blue',
        'factory-blue',
        'workshop-blue',
        'trade-blue',
      ],
      saturated: [
        'sapphire',
        'lapis',
        'lazuli',
        'ultramarine',
        'cobalt',
        'smalt',
        'azurite',
        'blue-john',
        'sodalite',
        'dumortierite',
      ],
      vivid: [
        'electric-blue-dark',
        'laser-blue',
        'plasma-blue',
        'neon-blue-dark',
        'fluorescent-blue-dark',
        'phosphor-blue',
        'luminous-blue-dark',
        'glowing-blue-dark',
        'radiant-blue-dark',
        'brilliant-blue-dark',
      ],
    },
    mid: {
      muted: [
        'cadet',
        'air-force',
        'uniform',
        'service',
        'utility',
        'wedgwood',
        'delft',
        'faience',
        'majolica',
        'ceramic-blue',
      ],
      moderate: [
        'steel',
        'titanium-blue',
        'alloy-blue',
        'metal-blue',
        'chrome-blue',
        'nickel-blue',
        'silver-blue',
        'platinum-blue',
        'palladium-blue',
        'rhodium-blue',
      ],
      saturated: [
        'true-blue',
        'blue',
        'primary-blue',
        'pure-blue',
        'essential-blue',
        'fundamental-blue',
        'base-blue',
        'standard-blue',
        'reference-blue',
        'calibration-blue',
      ],
      vivid: [
        'electric',
        'neon-blue',
        'laser',
        'plasma',
        'fluorescent-blue',
        'phosphor',
        'luminous-blue',
        'glowing-blue',
        'radiant-blue',
        'brilliant-blue',
      ],
    },
    light: {
      muted: [
        'powder-blue',
        'baby-blue',
        'soft-blue',
        'gentle-blue',
        'quiet-blue',
        'calm-blue',
        'serene-blue',
        'peaceful-blue',
        'tranquil-blue',
        'restful-blue',
      ],
      moderate: [
        'sky',
        'daylight',
        'clear-sky',
        'fair-sky',
        'fine-sky',
        'bright-sky',
        'morning-sky',
        'noon-sky',
        'afternoon-sky',
        'golden-hour-blue',
      ],
      saturated: [
        'cornflower',
        'periwinkle-blue',
        'bluebell',
        'forget-me-not',
        'larkspur',
        'delphinium',
        'bachelor-button',
        'chicory',
        'borage',
        'viper-bugloss',
      ],
      vivid: [
        'electric-blue-light',
        'neon-sky',
        'laser-blue-light',
        'plasma-sky',
        'fluorescent-sky',
        'phosphor-sky',
        'luminous-sky',
        'glowing-sky',
        'radiant-sky',
        'brilliant-sky',
      ],
    },
    veryLight: {
      muted: [
        'ice-blue',
        'frost-blue',
        'winter-blue',
        'snow-blue',
        'glacier-blue-light',
        'arctic-blue-light',
        'polar-blue',
        'frozen-blue',
        'crystal-blue',
        'diamond-blue',
      ],
      moderate: [
        'pale-blue',
        'light-blue',
        'sky-blue-light',
        'heaven-blue',
        'celestial-blue',
        'ethereal-blue',
        'angelic-blue',
        'divine-blue',
        'sacred-blue',
        'holy-blue',
      ],
      saturated: [
        'bright-sky',
        'vivid-sky',
        'intense-sky',
        'strong-sky',
        'powerful-sky',
        'dynamic-sky',
        'energetic-sky',
        'active-sky',
        'vital-sky',
        'living-sky',
      ],
      vivid: [
        'neon-ice',
        'electric-ice',
        'laser-ice',
        'plasma-ice',
        'fluorescent-ice',
        'phosphor-ice',
        'luminous-ice',
        'glowing-ice',
        'radiant-ice',
        'brilliant-ice',
      ],
    },
  },
  cool: {
    veryDark: {
      muted: [
        'ink',
        'charcoal-blue',
        'shadow-blue',
        'eclipse-blue',
        'void-blue',
        'abyss-blue',
        'deep-space',
        'cosmos-blue',
        'universe-blue',
        'infinity-blue',
      ],
      moderate: [
        'midnight-blue',
        'night-blue',
        'evening-blue',
        'dusk-blue',
        'twilight-blue',
        'gloaming-blue',
        'crepuscular-blue',
        'nocturnal-blue',
        'dark-hours',
        'witching-blue',
      ],
      saturated: [
        'ocean-deep',
        'abyssal',
        'hadal',
        'trench-blue',
        'mariana',
        'deep-sea',
        'bathyal',
        'benthic',
        'pelagic-dark',
        'oceanic-dark',
      ],
      vivid: [
        'bioluminescent-dark',
        'deep-glow-ocean',
        'abyssal-light',
        'trench-glow',
        'hadal-light',
        'deep-phosphor',
        'ocean-phosphor',
        'sea-glow-dark',
        'marine-light-dark',
        'aquatic-glow-dark',
      ],
    },
    dark: {
      muted: [
        'ocean-gray',
        'sea-fog',
        'marine-mist',
        'nautical-gray',
        'maritime-blue',
        'coastal-gray',
        'shore-blue',
        'harbor-blue',
        'port-blue',
        'dock-blue',
      ],
      moderate: [
        'ocean',
        'sea',
        'marine',
        'nautical',
        'maritime',
        'naval-cool',
        'fleet-blue',
        'armada-blue',
        'flotilla-blue',
        'squadron-blue',
      ],
      saturated: [
        'deep-ocean',
        'deep-sea-cool',
        'deep-marine',
        'deep-nautical',
        'deep-maritime',
        'atlantic',
        'pacific-blue',
        'indian-ocean',
        'southern-ocean',
        'arctic-ocean',
      ],
      vivid: [
        'electric-ocean',
        'neon-sea',
        'laser-marine',
        'plasma-ocean',
        'fluorescent-sea',
        'phosphor-marine',
        'luminous-ocean',
        'glowing-sea',
        'radiant-marine',
        'brilliant-ocean',
      ],
    },
    mid: {
      muted: [
        'sea-blue',
        'wave-blue',
        'surf-blue',
        'tide-blue',
        'current-blue',
        'flow-blue',
        'stream-blue',
        'river-blue',
        'creek-blue',
        'brook-blue',
      ],
      moderate: [
        'azure',
        'cerulean',
        'peacock-blue',
        'teal-blue',
        'duck-blue',
        'mallard',
        'kingfisher',
        'heron-blue',
        'crane-blue',
        'egret-blue',
      ],
      saturated: [
        'bright-ocean',
        'vivid-sea',
        'intense-marine',
        'strong-nautical',
        'powerful-maritime',
        'dynamic-ocean',
        'energetic-sea',
        'active-marine',
        'vital-ocean',
        'living-sea',
      ],
      vivid: [
        'electric-azure',
        'neon-cerulean',
        'laser-peacock',
        'plasma-teal',
        'fluorescent-azure',
        'phosphor-cerulean',
        'luminous-azure',
        'glowing-cerulean',
        'radiant-azure',
        'brilliant-cerulean',
      ],
    },
    light: {
      muted: [
        'seafoam-blue',
        'spray-blue',
        'mist-blue',
        'vapor-blue',
        'steam-blue',
        'cloud-blue',
        'wisp-blue',
        'breath-blue',
        'whisper-blue',
        'sigh-blue',
      ],
      moderate: [
        'aquamarine-light',
        'pool-blue',
        'lagoon-blue',
        'cove-blue',
        'bay-blue',
        'inlet-blue',
        'sound-blue',
        'strait-blue',
        'channel-blue',
        'passage-blue',
      ],
      saturated: [
        'bright-aqua',
        'vivid-pool',
        'intense-lagoon',
        'strong-cove',
        'powerful-bay',
        'dynamic-inlet',
        'energetic-pool',
        'active-lagoon',
        'vital-cove',
        'living-bay',
      ],
      vivid: [
        'electric-aqua',
        'neon-pool',
        'laser-lagoon',
        'plasma-cove',
        'fluorescent-bay',
        'phosphor-inlet',
        'luminous-pool',
        'glowing-lagoon',
        'radiant-cove',
        'brilliant-bay',
      ],
    },
    veryLight: {
      muted: [
        'glacier',
        'iceberg',
        'floe',
        'pack-ice',
        'shelf-ice',
        'berg-blue',
        'calving-blue',
        'melt-blue',
        'thaw-blue',
        'spring-ice',
      ],
      moderate: [
        'arctic',
        'antarctic',
        'polar-cool',
        'boreal-blue',
        'northern-blue',
        'southern-blue',
        'circumpolar',
        'subarctic',
        'subantarctic',
        'periglacial',
      ],
      saturated: [
        'bright-glacier',
        'vivid-ice',
        'intense-arctic',
        'strong-polar',
        'powerful-boreal',
        'dynamic-glacier',
        'energetic-ice',
        'active-arctic',
        'vital-polar',
        'living-glacier',
      ],
      vivid: [
        'neon-glacier',
        'electric-arctic',
        'laser-polar',
        'plasma-boreal',
        'fluorescent-glacier',
        'phosphor-arctic',
        'luminous-glacier',
        'glowing-arctic',
        'radiant-glacier',
        'brilliant-arctic',
      ],
    },
  },
  neutral: {
    veryDark: {
      muted: [
        'charcoal-indigo',
        'graphite-blue',
        'carbon-blue',
        'mineral-blue-dark',
        'stone-blue-dark',
        'rock-blue',
        'slate-dark',
        'shale-blue',
        'basalt-blue',
        'granite-blue',
      ],
      moderate: [
        'indigo',
        'woad',
        'natural-indigo',
        'plant-indigo',
        'organic-indigo',
        'true-indigo',
        'pure-indigo',
        'essential-indigo',
        'fundamental-indigo',
        'base-indigo',
      ],
      saturated: [
        'deep-indigo',
        'rich-indigo',
        'full-indigo',
        'saturated-indigo',
        'intense-indigo',
        'strong-indigo',
        'powerful-indigo',
        'dynamic-indigo',
        'energetic-indigo',
        'vital-indigo',
      ],
      vivid: [
        'vivid-indigo',
        'brilliant-indigo',
        'radiant-indigo',
        'glowing-indigo',
        'luminous-indigo',
        'phosphor-indigo',
        'fluorescent-indigo',
        'neon-indigo',
        'electric-indigo',
        'laser-indigo',
      ],
    },
    dark: {
      muted: [
        'mineral-blue',
        'stone-blue',
        'pebble-blue',
        'gravel-blue',
        'sand-blue',
        'earth-blue',
        'soil-blue',
        'clay-blue',
        'loam-blue',
        'humus-blue',
      ],
      moderate: [
        'natural-blue',
        'organic-blue',
        'eco-blue',
        'green-blue',
        'sustainable-blue',
        'renewable-blue',
        'recycled-blue',
        'upcycled-blue',
        'repurposed-blue',
        'reclaimed-blue',
      ],
      saturated: [
        'spectrum-blue-dark',
        'balanced-blue-dark',
        'centered-blue',
        'median-blue',
        'middle-blue',
        'mean-blue',
        'average-blue',
        'typical-blue',
        'common-blue',
        'standard-blue-dark',
      ],
      vivid: [
        'spectrum-vivid-dark',
        'balanced-vivid',
        'centered-vivid',
        'median-vivid',
        'middle-vivid',
        'mean-vivid',
        'average-vivid',
        'typical-vivid',
        'common-vivid',
        'standard-vivid',
      ],
    },
    mid: {
      muted: [
        'linen-blue',
        'cotton-blue',
        'hemp-blue',
        'flax-blue',
        'jute-blue',
        'sisal-blue',
        'ramie-blue',
        'bamboo-blue',
        'silk-blue',
        'wool-blue',
      ],
      moderate: [
        'textile-blue',
        'fabric-blue',
        'cloth-blue',
        'weave-blue',
        'thread-blue',
        'yarn-blue',
        'fiber-blue',
        'filament-blue',
        'strand-blue',
        'string-blue',
      ],
      saturated: [
        'spectrum-blue',
        'balanced-blue',
        'neutral-blue',
        'even-blue',
        'equal-blue',
        'fair-blue',
        'just-blue',
        'right-blue',
        'true-blue-neutral',
        'pure-blue-neutral',
      ],
      vivid: [
        'vivid-spectrum',
        'brilliant-balanced',
        'radiant-neutral',
        'glowing-even',
        'luminous-equal',
        'phosphor-fair',
        'fluorescent-just',
        'neon-right',
        'electric-true',
        'laser-pure',
      ],
    },
    light: {
      muted: [
        'linen-light',
        'cotton-light',
        'muslin-blue',
        'gauze-blue',
        'voile-blue',
        'chiffon-blue',
        'organza-blue',
        'tulle-blue',
        'lace-blue',
        'mesh-blue',
      ],
      moderate: [
        'canvas-blue',
        'sailcloth',
        'duck-cloth',
        'twill-blue',
        'denim-light',
        'chambray',
        'oxford-blue',
        'poplin-blue',
        'broadcloth-blue',
        'percale-blue',
      ],
      saturated: [
        'bright-neutral-blue',
        'vivid-balanced',
        'intense-even',
        'strong-equal',
        'powerful-fair',
        'dynamic-just',
        'energetic-right',
        'active-true',
        'vital-pure',
        'living-neutral',
      ],
      vivid: [
        'brilliant-neutral',
        'radiant-balanced',
        'glowing-even',
        'luminous-equal',
        'phosphor-neutral',
        'fluorescent-balanced',
        'neon-even',
        'electric-equal',
        'laser-fair',
        'plasma-just',
      ],
    },
    veryLight: {
      muted: [
        'white-blue',
        'milk-blue',
        'cream-blue',
        'ivory-blue',
        'bone-blue',
        'chalk-blue',
        'snow-blue-light',
        'frost-white-blue',
        'ice-white',
        'crystal-white',
      ],
      moderate: [
        'pale-neutral-blue',
        'light-neutral',
        'fair-neutral',
        'clear-neutral',
        'clean-neutral',
        'pure-neutral',
        'fresh-neutral',
        'new-neutral',
        'young-neutral',
        'spring-neutral',
      ],
      saturated: [
        'bright-white-blue',
        'vivid-white-blue',
        'intense-white-blue',
        'strong-white-blue',
        'powerful-white-blue',
        'dynamic-white-blue',
        'energetic-white-blue',
        'active-white-blue',
        'vital-white-blue',
        'living-white-blue',
      ],
      vivid: [
        'brilliant-white-blue',
        'radiant-white-blue',
        'glowing-white-blue',
        'luminous-white-blue',
        'phosphor-white-blue',
        'fluorescent-white-blue',
        'neon-white-blue',
        'electric-white-blue',
        'laser-white-blue',
        'plasma-white-blue',
      ],
    },
  },
};

/**
 * Green Hub (120-140°)
 * Core semantic: nature, growth, life, freshness, environment
 */
export const GREEN_HUB: HueHub = {
  warm: {
    veryDark: {
      muted: [
        'dark-moss',
        'deep-forest',
        'shadowed-fern',
        'black-pine',
        'dark-spruce',
        'night-forest',
        'woodland-shadow',
        'thicket-dark',
        'grove-shadow',
        'copse-dark',
      ],
      moderate: [
        'forest',
        'pine',
        'spruce',
        'fir',
        'hemlock',
        'cedar-green',
        'juniper',
        'cypress',
        'yew',
        'redwood-green',
      ],
      saturated: [
        'emerald-dark',
        'malachite-dark',
        'jade-dark',
        'serpentine',
        'nephrite-dark',
        'jadeite-dark',
        'aventurine-dark',
        'chrysoprase-dark',
        'peridot-dark',
        'olivine-dark',
      ],
      vivid: [
        'neon-forest',
        'electric-pine',
        'laser-spruce',
        'plasma-fir',
        'fluorescent-forest',
        'phosphor-pine',
        'luminous-forest',
        'glowing-pine',
        'radiant-forest',
        'brilliant-pine',
      ],
    },
    dark: {
      muted: [
        'olive-dark',
        'khaki-dark',
        'military',
        'army',
        'fatigues',
        'camouflage',
        'hunting',
        'safari-dark',
        'expedition',
        'field-green',
      ],
      moderate: [
        'hunter',
        'bottle',
        'racing-green',
        'british-racing',
        'jaguar',
        'aston-green',
        'bentley-green',
        'rolls-green',
        'vintage-racing',
        'classic-racing',
      ],
      saturated: [
        'emerald',
        'malachite',
        'jade',
        'imperial-jade',
        'burmese-jade',
        'chinese-jade',
        'celadon-dark',
        'verdant',
        'viridian-dark',
        'chlorophyll',
      ],
      vivid: [
        'electric-emerald',
        'neon-jade',
        'laser-malachite',
        'plasma-emerald',
        'fluorescent-jade',
        'phosphor-malachite',
        'luminous-emerald',
        'glowing-jade',
        'radiant-malachite',
        'brilliant-emerald',
      ],
    },
    mid: {
      muted: [
        'sage-warm',
        'dusty-sage',
        'dried-herb',
        'herb-garden',
        'kitchen-herb',
        'culinary-sage',
        'cooking-green',
        'seasoning-green',
        'spice-green',
        'flavor-green',
      ],
      moderate: [
        'fern',
        'bracken',
        'frond',
        'leaf',
        'foliage',
        'canopy',
        'understory',
        'forest-floor',
        'woodland',
        'grove',
      ],
      saturated: [
        'green',
        'true-green',
        'primary-green',
        'pure-green',
        'essential-green',
        'fundamental-green',
        'base-green',
        'standard-green',
        'reference-green',
        'calibration-green',
      ],
      vivid: [
        'electric-green',
        'neon-green',
        'laser-green',
        'plasma-green',
        'fluorescent-green',
        'phosphor-green',
        'luminous-green',
        'glowing-green',
        'radiant-green',
        'brilliant-green',
      ],
    },
    light: {
      muted: [
        'tea-green',
        'matcha-light',
        'sencha',
        'gyokuro',
        'tencha',
        'kukicha',
        'genmaicha',
        'hojicha-green',
        'bancha',
        'shincha',
      ],
      moderate: [
        'spring-green',
        'new-leaf',
        'fresh-leaf',
        'young-leaf',
        'tender-leaf',
        'baby-leaf',
        'sprout',
        'shoot',
        'bud-green',
        'growth',
      ],
      saturated: [
        'bright-green',
        'vivid-green',
        'intense-green',
        'strong-green',
        'powerful-green',
        'dynamic-green',
        'energetic-green',
        'active-green',
        'vital-green',
        'living-green',
      ],
      vivid: [
        'electric-spring',
        'neon-leaf',
        'laser-sprout',
        'plasma-growth',
        'fluorescent-spring',
        'phosphor-leaf',
        'luminous-spring',
        'glowing-leaf',
        'radiant-spring',
        'brilliant-leaf',
      ],
    },
    veryLight: {
      muted: [
        'pale-sage',
        'whisper-green',
        'ghost-green',
        'mist-green',
        'fog-green',
        'vapor-green',
        'breath-green',
        'sigh-green',
        'dream-green',
        'ethereal-green',
      ],
      moderate: [
        'mint-cream',
        'spearmint-light',
        'peppermint-light',
        'wintergreen-light',
        'menthol-light',
        'eucalyptus-light',
        'tea-tree-light',
        'herbal-cream',
        'botanical-cream',
        'garden-cream',
      ],
      saturated: [
        'bright-mint',
        'vivid-spearmint',
        'intense-peppermint',
        'strong-wintergreen',
        'powerful-menthol',
        'dynamic-eucalyptus',
        'energetic-mint',
        'active-spearmint',
        'vital-peppermint',
        'living-wintergreen',
      ],
      vivid: [
        'neon-mint',
        'electric-spearmint',
        'laser-peppermint',
        'plasma-wintergreen',
        'fluorescent-mint',
        'phosphor-spearmint',
        'luminous-mint',
        'glowing-spearmint',
        'radiant-mint',
        'brilliant-mint',
      ],
    },
  },
  cool: {
    veryDark: {
      muted: [
        'swamp',
        'bog',
        'marsh',
        'fen',
        'moor',
        'wetland',
        'bayou',
        'slough',
        'quagmire',
        'morass',
      ],
      moderate: [
        'jungle-dark',
        'rainforest-dark',
        'tropical-dark',
        'equatorial',
        'amazonian-dark',
        'congo-dark',
        'borneo-dark',
        'sumatra-dark',
        'java-dark',
        'sulawesi-dark',
      ],
      saturated: [
        'deep-jungle',
        'deep-rainforest',
        'deep-tropical',
        'deep-equatorial',
        'deep-amazonian',
        'verdure-dark',
        'viridescence-dark',
        'chlorosis-dark',
        'photosynthesis-dark',
        'biosynthesis-dark',
      ],
      vivid: [
        'bioluminescent-green',
        'deep-glow-forest',
        'jungle-phosphor',
        'rainforest-glow',
        'tropical-luminous',
        'equatorial-radiant',
        'amazonian-brilliant',
        'congo-electric',
        'borneo-neon',
        'sumatra-laser',
      ],
    },
    dark: {
      muted: [
        'seaweed',
        'kelp',
        'algae',
        'plankton-green',
        'pond-green',
        'lake-green',
        'river-green',
        'stream-green',
        'creek-green',
        'brook-green',
      ],
      moderate: [
        'amazon',
        'congo',
        'borneo',
        'sumatra',
        'java',
        'sulawesi',
        'papua',
        'madagascar',
        'caribbean-green',
        'pacific-green',
      ],
      saturated: [
        'jungle',
        'rainforest',
        'tropical',
        'equatorial-cool',
        'amazonian',
        'verdure',
        'viridescence',
        'chlorosis',
        'photosynthesis',
        'biosynthesis',
      ],
      vivid: [
        'electric-jungle',
        'neon-rainforest',
        'laser-tropical',
        'plasma-equatorial',
        'fluorescent-amazonian',
        'phosphor-verdure',
        'luminous-jungle',
        'glowing-rainforest',
        'radiant-tropical',
        'brilliant-equatorial',
      ],
    },
    mid: {
      muted: [
        'lichen',
        'patina-green',
        'verdigris',
        'oxidized',
        'weathered-copper',
        'aged-bronze',
        'antique-brass',
        'old-penny',
        'statue-green',
        'monument-green',
      ],
      moderate: [
        'teal-green',
        'viridian',
        'veronese',
        'paolo-veronese',
        'hooker',
        'sap-green',
        'terre-verte',
        'chrome-oxide',
        'cobalt-green',
        'phthalo-green',
      ],
      saturated: [
        'bright-teal-green',
        'vivid-viridian',
        'intense-veronese',
        'strong-hooker',
        'powerful-sap',
        'dynamic-terre',
        'energetic-chrome',
        'active-cobalt',
        'vital-phthalo',
        'living-viridian',
      ],
      vivid: [
        'electric-viridian',
        'neon-veronese',
        'laser-hooker',
        'plasma-sap',
        'fluorescent-terre',
        'phosphor-chrome',
        'luminous-viridian',
        'glowing-veronese',
        'radiant-hooker',
        'brilliant-sap',
      ],
    },
    light: {
      muted: [
        'seafoam',
        'sea-glass',
        'beach-glass',
        'wave-glass',
        'tide-green',
        'surf-green',
        'spray-green',
        'foam-green',
        'bubble-green',
        'froth-green',
      ],
      moderate: [
        'aquamarine',
        'turquoise-green',
        'caribbean-turquoise',
        'tropical-sea',
        'island-water',
        'lagoon-green',
        'cove-green',
        'bay-green',
        'inlet-green',
        'sound-green',
      ],
      saturated: [
        'bright-seafoam',
        'vivid-aquamarine',
        'intense-turquoise',
        'strong-caribbean',
        'powerful-tropical',
        'dynamic-island',
        'energetic-lagoon',
        'active-cove',
        'vital-bay',
        'living-inlet',
      ],
      vivid: [
        'electric-seafoam',
        'neon-aquamarine',
        'laser-turquoise',
        'plasma-caribbean',
        'fluorescent-tropical',
        'phosphor-island',
        'luminous-seafoam',
        'glowing-aquamarine',
        'radiant-turquoise',
        'brilliant-caribbean',
      ],
    },
    veryLight: {
      muted: [
        'glacier-green',
        'ice-green',
        'frost-green',
        'snow-green',
        'winter-green-light',
        'arctic-green',
        'polar-green',
        'frozen-green',
        'crystal-green',
        'diamond-green',
      ],
      moderate: [
        'mint',
        'spearmint',
        'peppermint',
        'wintergreen',
        'menthol',
        'eucalyptus',
        'tea-tree',
        'herbal',
        'botanical',
        'aromatic-green',
      ],
      saturated: [
        'bright-glacier-green',
        'vivid-ice-green',
        'intense-frost-green',
        'strong-snow-green',
        'powerful-winter-green',
        'dynamic-arctic-green',
        'energetic-polar-green',
        'active-frozen-green',
        'vital-crystal-green',
        'living-diamond-green',
      ],
      vivid: [
        'neon-glacier-green',
        'electric-ice-green',
        'laser-frost-green',
        'plasma-snow-green',
        'fluorescent-winter-green',
        'phosphor-arctic-green',
        'luminous-glacier-green',
        'glowing-ice-green',
        'radiant-frost-green',
        'brilliant-snow-green',
      ],
    },
  },
  neutral: {
    veryDark: {
      muted: [
        'charcoal-green',
        'graphite-green',
        'carbon-green',
        'mineral-green',
        'stone-green',
        'rock-green',
        'slate-green',
        'shale-green',
        'basalt-green',
        'granite-green',
      ],
      moderate: [
        'dark-olive',
        'deep-olive',
        'black-olive',
        'kalamata',
        'nicoise',
        'mission-olive',
        'manzanilla-dark',
        'gordal-dark',
        'picholine-dark',
        'lucques-dark',
      ],
      saturated: [
        'deep-herb',
        'rich-herb',
        'full-herb',
        'saturated-herb',
        'intense-herb',
        'strong-herb',
        'powerful-herb',
        'dynamic-herb',
        'energetic-herb',
        'vital-herb',
      ],
      vivid: [
        'vivid-herb',
        'brilliant-herb',
        'radiant-herb',
        'glowing-herb',
        'luminous-herb',
        'phosphor-herb',
        'fluorescent-herb',
        'neon-herb',
        'electric-herb',
        'laser-herb',
      ],
    },
    dark: {
      muted: [
        'olive',
        'olive-drab',
        'army-green',
        'military-green',
        'fatigues-green',
        'camouflage-green',
        'hunting-green',
        'safari',
        'expedition-green',
        'field',
      ],
      moderate: [
        'artichoke',
        'asparagus',
        'avocado',
        'kale',
        'spinach',
        'chard',
        'collard',
        'mustard-green',
        'turnip-green',
        'beet-green',
      ],
      saturated: [
        'spectrum-green-dark',
        'balanced-green-dark',
        'centered-green',
        'median-green',
        'middle-green',
        'mean-green',
        'average-green',
        'typical-green',
        'common-green',
        'standard-green-dark',
      ],
      vivid: [
        'spectrum-vivid-green-dark',
        'balanced-vivid-green',
        'centered-vivid-green',
        'median-vivid-green',
        'middle-vivid-green',
        'mean-vivid-green',
        'average-vivid-green',
        'typical-vivid-green',
        'common-vivid-green',
        'standard-vivid-green',
      ],
    },
    mid: {
      muted: [
        'sage',
        'thyme',
        'rosemary',
        'basil',
        'oregano',
        'marjoram',
        'tarragon',
        'chervil',
        'parsley',
        'cilantro',
      ],
      moderate: [
        'herb',
        'garden-green',
        'vegetable',
        'produce',
        'market-green',
        'farm-green',
        'orchard-green',
        'grove-green',
        'field-green-neutral',
        'meadow',
      ],
      saturated: [
        'spectrum-green',
        'balanced-green',
        'neutral-green',
        'even-green',
        'equal-green',
        'fair-green',
        'just-green',
        'right-green',
        'true-green-neutral',
        'pure-green-neutral',
      ],
      vivid: [
        'vivid-spectrum-green',
        'brilliant-balanced-green',
        'radiant-neutral-green',
        'glowing-even-green',
        'luminous-equal-green',
        'phosphor-fair-green',
        'fluorescent-just-green',
        'neon-right-green',
        'electric-true-green',
        'laser-pure-green',
      ],
    },
    light: {
      muted: [
        'celadon',
        'pale-jade',
        'light-jade',
        'soft-jade',
        'gentle-jade',
        'quiet-jade',
        'calm-jade',
        'serene-jade',
        'peaceful-jade',
        'tranquil-jade',
      ],
      moderate: [
        'pistachio',
        'wasabi',
        'lime-light',
        'key-lime',
        'persian-lime',
        'kaffir-lime',
        'finger-lime',
        'buddha-hand',
        'yuzu-green',
        'sudachi',
      ],
      saturated: [
        'bright-neutral-green',
        'vivid-balanced-green',
        'intense-even-green',
        'strong-equal-green',
        'powerful-fair-green',
        'dynamic-just-green',
        'energetic-right-green',
        'active-true-green',
        'vital-pure-green',
        'living-neutral-green',
      ],
      vivid: [
        'brilliant-neutral-green',
        'radiant-balanced-green',
        'glowing-even-green',
        'luminous-equal-green',
        'phosphor-neutral-green',
        'fluorescent-balanced-green',
        'neon-even-green',
        'electric-equal-green',
        'laser-fair-green',
        'plasma-just-green',
      ],
    },
    veryLight: {
      muted: [
        'honeydew',
        'pale-green',
        'light-green',
        'soft-green',
        'gentle-green',
        'quiet-green',
        'calm-green',
        'serene-green',
        'peaceful-green',
        'tranquil-green',
      ],
      moderate: [
        'cucumber',
        'melon-green',
        'honeydew-melon',
        'galia',
        'casaba',
        'crenshaw',
        'canary-melon',
        'santa-claus-melon',
        'juan-canary',
        'piel-de-sapo',
      ],
      saturated: [
        'bright-white-green',
        'vivid-white-green',
        'intense-white-green',
        'strong-white-green',
        'powerful-white-green',
        'dynamic-white-green',
        'energetic-white-green',
        'active-white-green',
        'vital-white-green',
        'living-white-green',
      ],
      vivid: [
        'brilliant-white-green',
        'radiant-white-green',
        'glowing-white-green',
        'luminous-white-green',
        'phosphor-white-green',
        'fluorescent-white-green',
        'neon-white-green',
        'electric-white-green',
        'laser-white-green',
        'plasma-white-green',
      ],
    },
  },
};

// ============================================================================
// HUE HUB REGISTRY
// ============================================================================

/**
 * All hue hubs indexed by hue bucket (0-17)
 * Each bucket covers 20° of the hue wheel
 */
export const HUE_HUBS: Record<number, HueHub | undefined> = {
  0: RED_HUB, // 0-20° Red
  // 1: ORANGE_RED_HUB,    // 20-40° Orange-Red (TODO)
  // 2: ORANGE_HUB,        // 40-60° Orange (TODO)
  // 3: YELLOW_ORANGE_HUB, // 60-80° Yellow-Orange (TODO)
  // 4: YELLOW_HUB,        // 80-100° Yellow (TODO)
  // 5: YELLOW_GREEN_HUB,  // 100-120° Yellow-Green (TODO)
  6: GREEN_HUB, // 120-140° Green
  // 7: GREEN_CYAN_HUB,    // 140-160° Green-Cyan (TODO)
  // 8: CYAN_HUB,          // 160-180° Cyan (TODO)
  // 9: CYAN_BLUE_HUB,     // 180-200° Cyan-Blue (TODO)
  // 10: LIGHT_BLUE_HUB,   // 200-220° Light Blue (TODO)
  11: BLUE_HUB, // 220-240° Blue
  // 12: BLUE_VIOLET_HUB,  // 240-260° Blue-Violet (TODO)
  // 13: VIOLET_HUB,       // 260-280° Violet (TODO)
  // 14: PURPLE_HUB,       // 280-300° Purple (TODO)
  // 15: MAGENTA_HUB,      // 300-320° Magenta (TODO)
  // 16: PINK_HUB,         // 320-340° Pink (TODO)
  // 17: RED_PINK_HUB,     // 340-360° Red-Pink (TODO)
};

/**
 * Check if a hue bucket has an expanded hub available
 */
export function hasExpandedHub(hBucket: number): boolean {
  return HUE_HUBS[hBucket] !== undefined;
}

/**
 * Get material word from expanded hub if available
 * Falls back to undefined if hub doesn't exist
 */
export function getExpandedMaterialWord(
  hBucket: number,
  lBucket: number,
  cBucket: number,
  temperature: 'warm' | 'cool' | 'neutral',
  l: number,
  _c: number, // Reserved for future sub-selection based on chroma fraction
): string | undefined {
  const hub = HUE_HUBS[hBucket];
  if (!hub) return undefined;

  const lBand = getLightnessBand(lBucket);
  const cBand = getChromaBand(cBucket);

  const matrix = hub[temperature];
  const cell = matrix[lBand][cBand];

  // Use fractional L value to sub-select within the word list
  // L bucket size is 0.1
  const subIndex = getSubIndex(l, 0.1, cell.length);

  return cell[subIndex];
}
